version: '3.8'

services:

  db:
    image: mysql:8.0  # Usa la versión 8.0 de MySQL
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Cambia la contraseña del root
      MYSQL_DATABASE: vopper_db         # Nombre de la base de datos
      MYSQL_USER: vopper_user           # Usuario de la base de datos
      MYSQL_PASSWORD: userpassword      # Contraseña del usuario                
    networks:
      - vopper_network
    volumes:
      - db_data:/var/lib/mysql          # Volumen para persistencia de datos

  auth_module:
    build:
      context: ./Modules/Auth_Module
      dockerfile: Dockerfile  # Dockerfile en la carpeta Auth_Module
    expose:
      - "5072:8080"
    networks:
      - vopper_network
    depends_on:
      - db  # Dependencia en el servicio de la base de datos


  user_module:
    build:
      context: ./Modules/User_Module
      dockerfile: Dockerfile  # Dockerfile en la carpeta User_Module
    expose:
      - "5204:8080"
    networks:
      - vopper_network
    depends_on:
      - db  # Dependencia en el servicio de la base de datos

  gateway:
    build:
      context: ./Vopper_Gateway
      dockerfile: Dockerfile  # Dockerfile en la carpeta Vopper_Gateway
    ports:
      - "5175:8080"  # Expone el puerto 5000
    depends_on:
      - auth_module
      - user_module
    networks:
      - vopper_network

  

networks:
  vopper_network:
    driver: bridge

volumes:
  db_data:
