services:
  - type: web
    name: auth_module
    plan: free
    runtime: docker
    dockerfilePath: ./Modules/Auth_Module/Dockerfile
    dockerContext: ./Modules/Auth_Module
    envVars:
      - key: PORT
        value: 5072
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: vopper_user
      - key: DB_PASSWORD
        value: userpassword
      - key: DB_NAME
        value: vopper_db
 