services:
  - type: web  # Cambia a mysql si es necesario; Render tiene soporte para MySQL
    name: vopper_db
    env: docker
    plan: free  # Cambia a otro plan si es necesario
    image: mysql:8.0
    envVars:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vopper_db
      MYSQL_USER: vopper_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql  # Volumen para persistencia de datos

  - type: web
    name: auth_module
    env: docker
    plan: free
    dockerfilePath: ./Modules/Auth_Module/Dockerfile
    ports:
      - port: 5072
        targetPort: 8080
    dependsOn:
      - vopper_db

  - type: web
    name: user_module
    env: docker
    plan: free
    dockerfilePath: ./Modules/User_Module/Dockerfile
    ports:
      - port: 5204
        targetPort: 8080
    dependsOn:
      - vopper_db

  - type: web
    name: gateway
    env: docker
    plan: free
    dockerfilePath: ./Vopper_Gateway/Dockerfile
    ports:
      - port: 5175
        targetPort: 8080
    dependsOn:
      - auth_module
      - user_module

volumes:
  db_data:
