services:
  - type: web
    name: auth_module
    plan: free
    runtime: docker
    dockerfilePath: ./Modules/Auth_Module/Dockerfile
    dockerContext: ./Modules/Auth_Module
    envVars:
      - key: PORT
        value: 5072
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: vopper_user
      - key: DB_PASSWORD
        value: userpassword
      - key: DB_NAME
        value: vopper_db
  
  - type: web
    name: user_module
    plan: free
    runtime: docker
    dockerfilePath: ./Modules/User_Module/Dockerfile
    dockerContext: ./Modules/User_Module
    envVars:
      - key: PORT
        value: 5204
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: vopper_user
      - key: DB_PASSWORD
        value: userpassword
      - key: DB_NAME
        value: vopper_db
  
  - type: web
    name: gateway
    plan: free
    runtime: docker
    dockerfilePath: ./Vopper_Gateway/Dockerfile
    dockerContext: ./Vopper_Gateway
    envVars:
      - key: PORT
        value: 5175
      - key: AUTH_MODULE_URL
        value: http://auth_module:5072
      - key: USER_MODULE_URL
        value: http://user_module:5204
 